services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_dev
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data